/**
 * Extended content for each integration, keyed by integration slug.
 * Used on individual integration pages at /barnsley-ai/integrations/[slug].
 */
export const integrationContent = {
  // --- Chatbots and conversational AI ---

  voiceflow:
    'Voiceflow is a conversational AI design platform for building voice and chat agents. It provides a visual canvas for designing multi-turn conversation flows, with support for deploying to web chat, voice assistants, and messaging channels.\n\nI use Voiceflow when a project needs a structured conversation flow with branching logic - lead qualification bots, onboarding wizards, or customer support trees. The visual editor makes it straightforward to prototype and iterate on conversation design with non-technical stakeholders before going to production.\n\nFor Barnsley businesses, Voiceflow is a good fit when you need a chatbot that follows a defined process - like qualifying inbound enquiries, triaging support requests, or guiding users through a multi-step workflow. It integrates with CRMs, helpdesks, and custom APIs so the bot can pull and push data as part of the conversation.',

  botpress:
    'Botpress is an open-source AI chatbot builder with built-in support for LLMs and retrieval-augmented generation. It combines a visual flow editor with knowledge base grounding, so bots can answer questions based on your actual documentation.\n\nI use Botpress for customer support bots and internal Q&A systems where the bot needs to draw on a knowledge base rather than just follow a script. The RAG support means you can connect it to your docs, FAQs, or product manuals and get accurate, grounded answers.\n\nFor Barnsley businesses, Botpress works well for support automation - handling common queries, surfacing relevant help articles, and escalating to humans when needed. The open-source foundation gives you more control over data and deployment than fully hosted alternatives.',

  rasa: 'Rasa is a conversational AI framework built around intent classification and entity extraction. It gives you full control over the NLU pipeline, dialogue management, and deployment - making it the go-to for teams that need fine-grained control over their conversational AI.\n\nI use Rasa for projects that need custom intent models or where the conversation logic is complex enough to warrant a dedicated framework. It handles slot-filling, context management, and custom actions well, and the training pipeline is transparent enough to debug and improve over time.\n\nFor Barnsley businesses with specific domain vocabulary or complex conversational requirements, Rasa provides the flexibility to build exactly what you need rather than working within the constraints of a hosted platform.',

  dialogflow:
    "Dialogflow is Google's conversational AI platform for building voice and text agents. It provides natural language understanding, fulfillment via webhooks, and integrations with Google Assistant, telephony, and messaging platforms.\n\nI use Dialogflow when a project needs to integrate with the Google ecosystem or when telephony and voice channels are important. The NLU is solid for intent classification, and the fulfillment system connects to backend services for dynamic responses.\n\nFor Barnsley businesses that want phone-based IVR or voice assistants alongside web chat, Dialogflow provides a unified platform. It handles the NLU and channel management while your backend handles the business logic.",

  'amazon-lex':
    "Amazon Lex is AWS's service for building conversational interfaces with voice and text. It uses the same technology as Alexa and integrates natively with AWS Lambda, DynamoDB, and other AWS services.\n\nI use Amazon Lex for chatbot projects where the backend is already on AWS. The native Lambda integration means you can build sophisticated fulfillment logic without managing additional infrastructure, and the voice capabilities work well for IVR and telephony use cases.\n\nFor Barnsley businesses already running on AWS, Lex is a natural choice for adding conversational interfaces. It handles the speech recognition and NLU while Lambda functions handle the business logic - order lookups, booking systems, or internal tool queries.",

  flowise:
    'Flowise is an open-source LLM flow builder for creating conversational AI with RAG and tool use. It provides a drag-and-drop interface for connecting LLMs to knowledge bases, APIs, and external tools.\n\nI use Flowise for rapid prototyping of LLM-powered chatbots and for projects where the team wants a visual way to configure and iterate on AI flows without writing code for every change. It connects to vector databases, document loaders, and various LLM providers.\n\nFor Barnsley businesses, Flowise is a good starting point for building AI assistants that can answer questions from your documents, query your databases, or interact with your existing tools. The visual editor makes it easier to experiment with different retrieval strategies and LLM configurations.',

  // --- Search and retrieval ---

  marqo:
    'Marqo is an AI-powered search API with built-in embedding generation and hybrid retrieval. It handles the full search pipeline - from document ingestion and embedding to hybrid keyword and semantic search - in a single API.\n\nI use Marqo when I need to get semantic search running quickly without managing separate embedding and vector database infrastructure. It handles text and image search, supports filtering, and the API is straightforward to integrate into existing applications.\n\nFor Barnsley businesses looking to add intelligent search to their products or internal tools, Marqo reduces the complexity. You send in your documents and it handles embedding, indexing, and retrieval - so you can focus on the search experience rather than the infrastructure.',

  zilliz:
    'Zilliz is a managed vector database built on Milvus, designed for AI-powered semantic search at scale. It stores embeddings and runs similarity queries with filtering, supporting billions of vectors with low-latency retrieval.\n\nI use Zilliz for production search systems where scale and performance matter. When you have large document collections, product catalogues, or knowledge bases that need fast semantic search, Zilliz handles the vector storage and retrieval while you focus on the application layer.\n\nFor Barnsley businesses with substantial data - product catalogues, technical documentation, or historical records - Zilliz provides the vector infrastructure to power AI search that understands intent rather than just matching keywords.',

  pinecone:
    "Pinecone is a managed vector database purpose-built for RAG and neural search. It indexes embedding vectors for fast retrieval and supports metadata filtering, namespaces, and hybrid search.\n\nI use Pinecone as the vector store in RAG pipelines - the layer between your embeddings and your LLM that retrieves the most relevant context for each query. It's reliable, fast, and the API is clean enough to integrate in a few lines of code.\n\nFor Barnsley businesses building AI search or Q&A systems over their documents, Pinecone provides the retrieval backbone. You embed your documents, store them in Pinecone, and query it to find the most relevant content to feed into your LLM for accurate, grounded answers.",

  weaviate:
    "Weaviate is a vector database with built-in hybrid search that combines vector similarity with keyword matching. It can generate embeddings automatically and supports GraphQL queries, making it flexible for complex search use cases.\n\nI use Weaviate when a project benefits from hybrid search - combining the precision of keyword matching with the semantic understanding of vector search. The built-in embedding support simplifies the pipeline, and the GraphQL API gives you fine-grained control over queries and filtering.\n\nFor Barnsley businesses that need search across mixed content types - structured data alongside free text - Weaviate's hybrid approach catches what pure keyword or pure vector search would miss.",

  qdrant:
    'Qdrant is a vector database optimised for similarity search with advanced filtering. It supports payload-based filtering alongside vector queries, which is important when you need to combine semantic search with structured constraints.\n\nI use Qdrant for search systems that need to filter results by metadata while still ranking by semantic similarity - for example, finding similar products within a specific category, or searching documents filtered by date range or department.\n\nFor Barnsley businesses, Qdrant works well when your search needs combine "find something similar to X" with "but only within these constraints". It handles both efficiently in a single query.',

  llamaindex:
    'LlamaIndex is an AI data framework for building RAG applications. It provides document loaders, indexing strategies, and retrieval pipelines that connect your data to LLMs for question-answering, search, and summarisation.\n\nI use LlamaIndex to orchestrate the full retrieval pipeline - loading documents from various sources, chunking and indexing them, and retrieving the right context for each query. It supports multiple vector stores, embedding providers, and LLMs, so you can swap components as needed.\n\nFor Barnsley businesses building AI-powered Q&A or search over their own data, LlamaIndex handles the plumbing between your documents and the LLM. It manages the complexities of chunking, embedding, and retrieval so the AI gives accurate, grounded answers.',

  // --- Document processing ---

  'unstructured-io':
    "Unstructured.io provides AI-powered document parsing that extracts structured content from PDFs, images, HTML, and other document formats. It handles the messy reality of real-world documents - mixed layouts, tables, headers, and embedded images - and outputs clean, chunked content ready for LLM ingestion.\n\nI use Unstructured.io as the ingestion layer in document processing and RAG pipelines. It parses documents into structured elements (titles, paragraphs, tables, lists) that can be chunked and embedded for retrieval, or processed further for data extraction.\n\nFor Barnsley businesses dealing with high volumes of PDFs, scanned documents, or mixed-format archives, Unstructured.io is the first step in turning unstructured content into something AI can work with - whether that's powering search, extraction, or summarisation.",

  'amazon-textract':
    "Amazon Textract is AWS's AI document extraction service. It reads text, tables, and form data from documents and images, handling handwriting, complex layouts, and multi-page documents.\n\nI use Textract for extracting structured data from invoices, forms, and receipts - particularly when the documents have tabular data or form fields that need to be captured accurately. The AWS integration means extracted data flows naturally into Lambda functions, S3, and other services for downstream processing.\n\nFor Barnsley businesses processing invoices, delivery notes, or compliance forms, Textract automates the data entry that would otherwise require manual keying. It handles the extraction and your systems handle the validation and routing.",

  'google-document-ai':
    'Google Document AI provides ML models for extracting data from invoices, contracts, forms, and other business documents. It offers pre-trained processors for common document types and custom model training for specialised formats.\n\nI use Document AI when a project needs accurate extraction from specific document types - invoices, receipts, or contracts. The pre-trained models are accurate out of the box for common formats, and custom training handles domain-specific documents.\n\nFor Barnsley businesses in professional services, manufacturing, or logistics, Document AI can automate the extraction of key fields from routine documents - supplier details from invoices, terms from contracts, or quantities from order forms.',

  docugami:
    'Docugami is a document intelligence platform that understands the structure and semantics of business documents. It goes beyond simple extraction to understand relationships between clauses, terms, and concepts within contracts and business documents.\n\nI use Docugami for contract analysis and document understanding where the relationships between different parts of a document matter - not just extracting individual fields but understanding how clauses relate to each other and how terms compare across documents.\n\nFor Barnsley professional services firms handling contracts, Docugami provides deeper document intelligence than basic extraction tools. It can identify key terms, flag unusual clauses, and compare documents against your standards.',

  rossum:
    'Rossum is an AI document processing platform focused on invoices and purchase orders. It combines AI extraction with human-in-the-loop validation, so the system improves over time while maintaining accuracy.\n\nI use Rossum for high-volume invoice processing where accuracy matters and the system needs to handle varied supplier formats. The validation workflow means the AI handles the extraction while humans verify edge cases, and the system learns from corrections.\n\nFor Barnsley businesses processing large volumes of invoices or purchase orders, Rossum automates the bulk of data entry while keeping humans in the loop for quality assurance. It integrates with accounting and ERP systems for end-to-end automation.',

  sensible:
    "Sensible uses LLMs to extract structured data from documents with varied layouts. You define what you want to extract using natural language descriptions, and Sensible handles the rest - even when document formats change.\n\nI use Sensible for document extraction where layouts are inconsistent or frequently changing. Traditional template-based extraction breaks when formats shift; Sensible's LLM-powered approach adapts because it understands what the fields mean rather than where they appear on the page.\n\nFor Barnsley businesses receiving documents from multiple suppliers or sources with different formats, Sensible provides reliable extraction without maintaining a template for every variant.",

  // --- Workflow automation ---

  langchain:
    'LangChain is a framework for building applications with LLMs. It provides abstractions for prompt management, chains, agents, and tool use - the building blocks for multi-step AI workflows that interact with external systems.\n\nI use LangChain for building AI agents that need to call tools, query databases, and execute multi-step workflows. It handles the orchestration - deciding which tool to call, managing conversation state, and chaining multiple LLM calls together.\n\nFor Barnsley businesses, LangChain powers the agent layer in workflow automation: support ticket triage that queries your CRM, document processing that chains extraction with validation, or internal assistants that look up information across multiple systems.',

  crewai:
    'CrewAI is a multi-agent framework for delegating tasks between specialised AI agents. You define agents with different roles and tools, and CrewAI coordinates them to complete complex tasks through collaboration.\n\nI use CrewAI when a workflow benefits from multiple specialised agents working together - for example, a research agent that gathers information, an analysis agent that processes it, and a writing agent that produces the output. Each agent can have its own tools and instructions.\n\nFor Barnsley businesses with complex workflows involving multiple steps and different types of work, CrewAI provides a way to decompose the work into specialised agents that collaborate. This works well for processes like lead qualification, report generation, or multi-stage review.',

  autogen:
    "AutoGen is Microsoft's multi-agent framework for building autonomous AI conversations. It enables multiple AI agents to collaborate, debate, and iterate on tasks through structured conversations.\n\nI use AutoGen for workflows where multiple perspectives or iterative refinement improve the output - code review with multiple reviewer agents, content creation with writing and editing agents, or analysis that benefits from different analytical approaches.\n\nFor Barnsley businesses, AutoGen is useful when the AI workflow benefits from multiple passes or perspectives. Rather than a single-shot LLM call, you get a collaborative process that produces more reliable and thorough results.",

  'relevance-ai':
    'Relevance AI is an agent builder for creating autonomous AI workflows with tool use. It provides a no-code interface for defining agents that can call APIs, process data, and handle complex requests.\n\nI use Relevance AI when a project needs AI agents that interact with external tools and APIs, and the team wants to configure and iterate on agent behaviour without writing code for every change. It handles tool definitions, execution, and monitoring.\n\nFor Barnsley businesses looking to automate workflows with AI agents - handling inbound requests, processing data, or coordinating between systems - Relevance AI provides a platform to build and deploy agents without a full engineering effort.',

  'bolt-new':
    "Bolt.new is an AI-powered full-stack app builder that generates working applications from descriptions. It creates and deploys web applications with frontend, backend, and database components.\n\nI use Bolt.new for rapid prototyping of AI-powered tools and internal applications. When you need a working demo or proof of concept quickly, it can scaffold a functional application that you can then refine and extend.\n\nFor Barnsley businesses exploring AI, Bolt.new is useful for building quick prototypes that demonstrate what's possible before committing to a full build. It gets working software in front of stakeholders fast, so you can validate ideas and gather feedback.",

  steamship:
    'Steamship is an AI agent framework for building multi-step reasoning workflows with tool use. It handles the execution infrastructure for agents that need to call APIs, process files, and maintain state across interactions.\n\nI use Steamship for building persistent AI agents that need to maintain context and execute complex workflows over time - not just single-shot responses but multi-step processes that involve calling external tools and managing state.\n\nFor Barnsley businesses that need AI agents handling ongoing workflows - project coordination, ongoing monitoring, or multi-step approval processes - Steamship provides the execution infrastructure so the agents can operate reliably.',

  // --- Data pipelines and analytics ---

  'pandas-ai':
    'Pandas AI lets you query and manipulate dataframes using natural language. It translates plain English questions into pandas operations, making data exploration and analysis accessible to people who know their data but not Python.\n\nI use Pandas AI for exploratory data analysis and for building tools where non-technical users need to query datasets. It handles the translation from "show me sales by region for last quarter" into the appropriate pandas code.\n\nFor Barnsley businesses sitting on data in spreadsheets or databases, Pandas AI makes it possible to explore and analyse that data without specialist coding skills. It works well for ad-hoc analysis, reporting, and building internal data tools.',

  langsmith:
    "LangSmith is an observability and evaluation platform for LLM applications. It provides tracing, debugging, and evaluation tools so you can see exactly what your AI is doing and measure how well it's performing.\n\nI use LangSmith to trace and debug LLM pipelines - seeing the full chain of calls, prompts, and responses that led to a particular output. When something goes wrong or output quality drops, LangSmith shows you where in the pipeline the issue occurred.\n\nFor Barnsley businesses running AI in production, LangSmith provides the visibility to maintain quality over time. You can monitor for regressions, evaluate outputs against ground truth, and identify where the pipeline needs improvement.",

  haystack:
    'Haystack is an NLP framework by deepset for building LLM-powered pipelines. It provides modular components for document processing, retrieval, and generation that you compose into custom pipelines.\n\nI use Haystack for building document processing and retrieval pipelines where I need fine-grained control over each stage. The modular design means you can swap components - different retrievers, readers, or generators - without rewriting the pipeline.\n\nFor Barnsley businesses that need custom document processing - extraction, classification, summarisation, or search over domain-specific content - Haystack provides the building blocks to construct exactly the pipeline you need.',

  ragas:
    'Ragas is an evaluation framework for RAG pipelines. It measures retrieval quality, answer faithfulness, and overall pipeline performance with automated metrics.\n\nI use Ragas to evaluate and benchmark RAG systems before deployment and to monitor quality over time. It catches issues like the retriever missing relevant documents, the LLM hallucinating beyond the context, or answer quality degrading as the knowledge base changes.\n\nFor Barnsley businesses deploying AI search or Q&A systems, Ragas provides the quality assurance layer. You can measure whether the AI is actually retrieving the right information and generating accurate answers, rather than just hoping it works.',

  // --- Custom product features ---

  'vercel-ai-sdk':
    "The Vercel AI SDK provides React hooks and server utilities for building AI-powered user interfaces. It handles streaming responses, chat state management, and tool calling - the frontend plumbing for shipping AI features in React applications.\n\nI use the Vercel AI SDK for building chat interfaces, streaming completions, and interactive AI features in Next.js and React apps. It handles the complexity of streaming responses from multiple LLM providers with a consistent API.\n\nFor Barnsley businesses building AI-powered products or adding AI features to existing applications, the Vercel AI SDK provides the frontend layer. It connects your React UI to whatever LLM backend you're using and handles the real-time streaming that users expect from AI interactions.",

  cohere:
    "Cohere provides embedding and rerank APIs for building semantic search into products. The embeddings capture meaning from text, and the reranker improves search relevance by re-scoring results based on query relevance.\n\nI use Cohere's embed and rerank APIs when building search features into products. The two-stage approach - retrieve candidates with embeddings, then rerank for precision - produces noticeably better search results than embeddings alone.\n\nFor Barnsley businesses adding search to their products or internal tools, Cohere's reranking is often the single biggest improvement to search quality. It takes rough candidate results and puts the most relevant ones at the top.",

  'together-ai':
    "Together AI provides fast inference for open-source models via API. It runs popular models like Llama, Mistral, and others with competitive pricing and low latency.\n\nI use Together AI when a project needs open-source model inference without managing GPU infrastructure. The API is compatible with OpenAI's format, so switching between providers is straightforward. It's particularly useful for workloads where you want the flexibility of open models.\n\nFor Barnsley businesses building AI products, Together AI provides model inference at scale without the complexity and cost of running your own GPU servers. You get access to a range of models and can experiment to find the best fit for your use case.",

  openai:
    "OpenAI provides the GPT API for chat, embeddings, and assistive features. The models handle a wide range of language tasks - conversation, summarisation, classification, code generation, and more.\n\nI use OpenAI's API as one of several LLM providers depending on the task. GPT models are strong for general-purpose language tasks, function calling, and structured output. The embeddings API is useful for search and similarity features.\n\nFor Barnsley businesses integrating AI, OpenAI is often the starting point - well-documented, widely supported, and capable across a broad range of tasks. I help businesses integrate it effectively, manage costs, and evaluate whether alternative models might be a better fit for specific use cases.",

  anthropic:
    'Anthropic provides the Claude API for long-context and tool-use AI applications. Claude handles large documents, extended conversations, and complex reasoning with strong instruction-following and safety characteristics.\n\nI use the Claude API for tasks that benefit from long context windows - processing large documents, maintaining extended conversation history, or analysing multiple sources simultaneously. The tool-use capabilities power agent workflows where the AI needs to call external services.\n\nFor Barnsley businesses building AI products, Claude is particularly strong for document-heavy use cases, complex reasoning tasks, and applications where reliability and safety matter. The long context window means you can process full contracts, reports, or codebases in a single call.',

  'stability-ai':
    'Stability AI provides image generation and multimodal AI models. Their Stable Diffusion models handle text-to-image generation, image editing, and visual content creation.\n\nI use Stability AI when a product needs image generation or visual AI capabilities - product mockups, content imagery, or creative tools. The models can generate, edit, and transform images based on text descriptions.\n\nFor Barnsley businesses that need visual content at scale - e-commerce product imagery, marketing materials, or creative tools - Stability AI provides the generation capability. It can produce variations, edit existing images, and create visual content from descriptions.',

  // --- Computer vision and image AI ---

  roboflow:
    'Roboflow is a computer vision platform for training and deploying custom object detection and classification models. It handles the full pipeline from data labelling and augmentation to model training and deployment.\n\nI use Roboflow for projects that need custom vision models - defect detection on production lines, product classification, or visual inspection systems. The labelling tools and training pipeline make it practical to build accurate models from your own images.\n\nFor Barnsley manufacturers and quality-focused businesses, Roboflow makes custom visual inspection feasible. You label examples of good and defective products, train a model, and deploy it to inspect items in real-time on the production line.',

  clarifai:
    'Clarifai provides pre-built and custom AI models for image and video recognition. It offers ready-to-use models for common tasks alongside the ability to train custom models on your own data.\n\nI use Clarifai when a project needs image recognition capabilities without building from scratch. The pre-trained models handle common tasks - object detection, image classification, visual search - while custom training adapts to domain-specific needs.\n\nFor Barnsley businesses needing to classify, tag, or analyse images and video, Clarifai provides a fast path to working AI vision without deep ML expertise. It works well for content moderation, product tagging, and visual quality checks.',

  'google-cloud-vision':
    'Google Cloud Vision provides image analysis APIs for object detection, text extraction (OCR), label detection, and content classification. It handles the common vision tasks via straightforward API calls.\n\nI use Google Cloud Vision for projects that need reliable OCR, label detection, or object identification without training custom models. The pre-trained models are accurate for general-purpose vision tasks and the API is well-documented.\n\nFor Barnsley businesses needing to extract text from images, classify visual content, or detect objects in photographs, Cloud Vision provides a reliable, production-ready solution that works through simple API calls.',

  'aws-rekognition':
    "AWS Rekognition is Amazon's image and video analysis service. It provides object detection, scene recognition, text extraction, and content moderation via API, integrated with the broader AWS ecosystem.\n\nI use Rekognition for vision tasks where the project is already on AWS infrastructure. It handles object detection, scene classification, and text extraction, with results flowing naturally into S3, Lambda, and other AWS services.\n\nFor Barnsley businesses running on AWS, Rekognition provides a natural way to add vision capabilities - analysing product images, extracting information from photos, or moderating user-uploaded content - without managing separate ML infrastructure.",

  replicate:
    'Replicate lets you run open-source AI models via API without managing infrastructure. It hosts thousands of community and commercial models for image generation, language, audio, and video tasks.\n\nI use Replicate for running open-source vision and generative models when I need capabilities beyond the big cloud APIs. The pay-per-prediction pricing means you only pay when you use it, and the model library covers a huge range of tasks.\n\nFor Barnsley businesses that need specialised AI capabilities - particular image styles, domain-specific models, or experimental architectures - Replicate provides access without the cost and complexity of managing GPU servers.',

  'hugging-face':
    "Hugging Face is the hub for open-source AI models, datasets, and inference. It hosts thousands of pre-trained models for text, vision, audio, and multimodal tasks, with libraries for training, fine-tuning, and deployment.\n\nI use Hugging Face for accessing pre-trained models, fine-tuning on custom data, and running inference via their API or self-hosted. The model hub makes it straightforward to find, evaluate, and deploy models for specific tasks.\n\nFor Barnsley businesses exploring AI, Hugging Face provides access to the full range of open-source models. Whether you need classification, generation, embedding, or a domain-specific model, it's usually the first place to look.",

  // --- Voice and speech AI ---

  'openai-whisper':
    "Whisper is OpenAI's speech-to-text model for transcription and translation. It handles multiple languages, accents, and noisy audio with high accuracy, running either via API or locally.\n\nI use Whisper for transcribing calls, meetings, and dictation. The accuracy is strong across different accents and audio qualities, and it handles technical vocabulary better than most alternatives. Running it locally means sensitive audio never leaves your infrastructure.\n\nFor Barnsley businesses needing transcription - customer call logging, meeting notes, or compliance recording - Whisper provides accurate speech-to-text that works with regional accents and domain-specific terminology.",

  elevenlabs:
    "ElevenLabs provides AI voice synthesis for natural-sounding text-to-speech. It generates speech that sounds human, with control over voice characteristics, emotion, and pacing.\n\nI use ElevenLabs for projects that need high-quality voice output - IVR systems, audio content, or voice assistants where natural-sounding speech matters. The voice cloning and customisation options let you create a consistent voice identity.\n\nFor Barnsley businesses building voice interfaces or audio content, ElevenLabs provides the text-to-speech layer. Whether it's an automated phone system, audio instructions, or an assistant that speaks, the voice quality is noticeably better than traditional TTS.",

  assemblyai:
    'AssemblyAI provides speech-to-text with built-in summarisation, sentiment analysis, and content moderation. It transcribes audio and video with additional NLP layers on top of the raw transcript.\n\nI use AssemblyAI when a project needs more than just transcription - when you also want summaries, key topics, sentiment, or speaker identification from the audio. The combined pipeline saves building these layers separately.\n\nFor Barnsley businesses analysing customer calls or meetings, AssemblyAI provides transcription plus insights in one API. You get the transcript and the analysis - sentiment trends, key topics, action items - without building a separate NLP pipeline.',

  deepgram:
    "Deepgram provides real-time speech recognition and transcription. It's optimised for low-latency streaming transcription, making it suitable for live conversations, real-time captioning, and voice-controlled applications.\n\nI use Deepgram for projects that need real-time transcription - live call analysis, real-time captioning, or voice interfaces where latency matters. The streaming API processes audio as it arrives rather than waiting for the full recording.\n\nFor Barnsley businesses needing live transcription - customer call monitoring, real-time meeting notes, or voice-controlled systems - Deepgram handles the real-time processing that batch transcription tools can't provide.",

  vapi: 'Vapi is a voice AI platform for building phone and voice assistants. It handles the full voice pipeline - speech recognition, LLM processing, and text-to-speech - integrated with telephony for phone-based AI agents.\n\nI use Vapi for building AI phone agents - systems that can answer calls, handle queries, and route to humans when needed. It manages the complexity of telephony, voice processing, and LLM integration in one platform.\n\nFor Barnsley businesses that want AI-powered phone support - handling common queries, booking appointments, or qualifying leads by phone - Vapi provides the platform to build voice agents that work over actual phone lines.',

  'google-cloud-speech':
    'Google Cloud Speech-to-Text and Text-to-Speech provide speech recognition and synthesis APIs. They support multiple languages, real-time streaming, and custom model adaptation for domain-specific vocabulary.\n\nI use Google Cloud Speech when a project needs robust speech processing within the Google Cloud ecosystem. The custom vocabulary and model adaptation features are useful for domain-specific terminology, and the streaming API handles real-time use cases.\n\nFor Barnsley businesses building voice-enabled applications on Google Cloud, the Speech APIs provide production-grade speech recognition and synthesis that integrates with the broader GCP platform.',

  // --- Predictive analytics and forecasting ---

  arize:
    'Arize is an ML observability platform for monitoring production models. It tracks model performance, detects drift, and helps diagnose when and why predictions degrade over time.\n\nI use Arize to monitor predictive models in production. When a demand forecast starts being wrong or a classification model drifts, Arize shows you what changed - was it the data distribution, a feature shift, or a model issue? This visibility is essential for maintaining model quality.\n\nFor Barnsley businesses running predictive analytics, Arize provides the monitoring layer that catches problems before they impact decisions. You see model performance in real-time and get alerted when something changes.',

  whylabs:
    "WhyLabs provides AI monitoring and data drift detection. It profiles your data and model outputs over time, alerting you when distributions shift or quality degrades.\n\nI use WhyLabs to monitor data pipelines and model inputs. Data drift is one of the main reasons ML models degrade in production - the real-world data changes and the model hasn't adapted. WhyLabs catches this early.\n\nFor Barnsley businesses with predictive analytics in production, WhyLabs provides early warning when your data or model behaviour changes. This means you can retrain or adjust before the predictions become unreliable.",

  fiddler:
    'Fiddler provides ML explainability and model monitoring. It explains why a model made a specific prediction and tracks model behaviour over time to catch issues.\n\nI use Fiddler when stakeholders need to understand why the AI makes specific decisions - not just the prediction but the reasoning. This is particularly important for regulated industries or high-stakes decisions where you need to justify the model\'s output.\n\nFor Barnsley businesses where AI decisions need to be explainable - lending, insurance, compliance, or any situation where "the algorithm said so" isn\'t enough - Fiddler provides the transparency layer.',

  prophet:
    "Prophet is Meta's time-series forecasting library for predicting trends with seasonality. It handles daily, weekly, and yearly patterns with minimal configuration, making it accessible for business forecasting.\n\nI use Prophet for demand forecasting, sales predictions, and capacity planning where the data has clear temporal patterns. It handles holidays, trend changes, and missing data gracefully, and the output is interpretable - you can see the trend, seasonality, and holiday components separately.\n\nFor Barnsley businesses that need forecasting - inventory planning, staffing, or revenue projections - Prophet provides accessible time-series prediction that accounts for the patterns in your data.",

  // --- Manufacturing and engineering ---

  augmentir:
    'Augmentir is an AI platform for frontline manufacturing workers. It provides digital work instructions, process guidance, and performance analytics to help workers execute procedures accurately and efficiently.\n\nI use Augmentir in manufacturing projects where standardising and digitising work instructions improves quality and reduces errors. The AI adapts instructions based on worker experience and tracks where mistakes happen most.\n\nFor Barnsley manufacturers, Augmentir helps bridge the skills gap by guiding workers through procedures step-by-step. As experienced staff retire, the system captures their knowledge and helps newer workers perform at the same standard.',

  'sight-machine':
    "Sight Machine provides manufacturing analytics and AI for quality and yield optimisation. It connects to production data sources and applies analytics to identify patterns that affect quality, efficiency, and output.\n\nI use Sight Machine for projects where production data needs to be analysed at scale to find root causes of quality issues or efficiency losses. It connects the data from machines, sensors, and quality systems into a unified analytics layer.\n\nFor Barnsley manufacturers looking to improve yield or reduce defects, Sight Machine provides the analytics to understand what's happening on the production line and why. It turns raw production data into actionable insights.",

  samsara:
    'Samsara is an AI-powered operations platform for industrial IoT and fleet management. It connects physical assets - vehicles, equipment, facilities - to a central platform for monitoring, automation, and analytics.\n\nI use Samsara when a project needs to bridge physical operations with digital systems. It handles the hardware connectivity and data collection while the AI layer provides route optimisation, safety monitoring, and predictive maintenance.\n\nFor Barnsley businesses in manufacturing, logistics, or field services, Samsara provides visibility into physical operations. It tracks equipment utilisation, monitors safety compliance, and provides data for operational improvements.',

  'siemens-industrial-ai':
    'Siemens provides industrial AI solutions for predictive maintenance and manufacturing optimisation. Their platform connects to industrial equipment and applies AI for condition monitoring, quality prediction, and process optimisation.\n\nI use Siemens AI tools in manufacturing projects where equipment reliability and process optimisation are critical. The industrial-grade integrations handle the complexity of connecting to PLCs, SCADA systems, and other industrial infrastructure.\n\nFor Barnsley manufacturers running Siemens equipment or looking for enterprise-grade predictive maintenance, their AI platform provides a proven path from equipment data to actionable maintenance predictions.',

  cognex:
    "Cognex provides machine vision and AI for quality inspection on production lines. Their systems handle defect detection, measurement verification, and assembly inspection at production speeds.\n\nI use Cognex vision systems for automated quality inspection where speed and accuracy matter. The hardware and software are designed for production environments - handling lighting variation, line speed, and the reliability requirements of manufacturing.\n\nFor Barnsley manufacturers doing visual quality inspection, Cognex provides production-proven systems that catch defects consistently. Automated inspection runs at line speed and doesn't have the variability of manual checks.",

  sparkcognition:
    'SparkCognition provides AI for predictive maintenance and industrial optimisation. It analyses sensor data and operational patterns to predict equipment failures before they happen and optimise asset performance.\n\nI use SparkCognition for predictive maintenance projects where the cost of unplanned downtime is high. The platform ingests sensor data, learns normal operating patterns, and alerts when equipment behaviour suggests an impending failure.\n\nFor Barnsley manufacturers, SparkCognition helps shift from reactive maintenance (fixing things when they break) to predictive maintenance (fixing things before they break). This reduces downtime and extends equipment life.',

  // --- Professional services ---

  harvey:
    "Harvey is an AI platform for legal research, contract analysis, and due diligence. It's built specifically for legal workflows, understanding legal concepts, citations, and document structures.\n\nI use Harvey for legal AI projects where the domain expertise matters. Generic LLMs can handle basic legal queries, but Harvey's specialisation means it understands legal nuance, citation formats, and the structure of legal arguments.\n\nFor Barnsley law firms and legal professionals, Harvey accelerates research and review workflows. It can analyse contracts, research precedents, and draft documents while maintaining the precision that legal work demands.",

  luminance:
    'Luminance provides AI-powered contract analysis and legal document review. It reads and understands contracts, identifying key terms, obligations, and potential issues across large document sets.\n\nI use Luminance for contract review projects where volume and consistency matter. It can process hundreds of contracts and flag the clauses that need human attention - unusual terms, missing protections, or deviations from your standards.\n\nFor Barnsley professional services firms handling contracts, Luminance provides the AI layer for review at scale. Instead of reading every page, your team focuses on the clauses the AI flags as requiring attention.',

  casetext:
    'Casetext, now part of Thomson Reuters, provides AI-powered legal research and brief analysis. It uses AI to search case law, analyse briefs, and surface relevant authorities.\n\nI use Casetext for legal research projects where finding the right precedents quickly is essential. The AI understands legal queries and surfaces relevant cases and authorities, saving hours of manual research.\n\nFor Barnsley legal professionals, Casetext makes research faster and more thorough. The AI searches across case law and surfaces relevant authorities that keyword search alone would miss.',

  kira: 'Kira Systems provides AI for contract review and due diligence. It extracts key provisions from contracts and identifies risks, obligations, and commercial terms across large document sets.\n\nI use Kira for due diligence and contract analysis projects. It handles the systematic extraction of terms from large contract portfolios - the kind of work that would take teams weeks to do manually.\n\nFor Barnsley professional services firms involved in transactions, property, or corporate work, Kira automates the extraction and review of key contract terms. It ensures nothing is missed in large document reviews.',

  evisort:
    'Evisort provides AI contract intelligence and lifecycle management. It combines extraction with ongoing contract management - tracking obligations, deadlines, and renewal dates across your entire contract portfolio.\n\nI use Evisort for projects where the goal is not just analysing contracts but managing them over time. The lifecycle management features mean you track obligations, get renewal alerts, and maintain visibility across your contract portfolio.\n\nFor Barnsley businesses managing multiple contracts, Evisort provides ongoing intelligence rather than one-time analysis. It extracts key clauses and then monitors deadlines, obligations, and renewal opportunities.',

  ironclad:
    'Ironclad provides contract lifecycle management with AI-powered extraction and workflow automation. It handles the full contract journey from creation and negotiation to execution, storage, and compliance tracking.\n\nI use Ironclad when a project needs end-to-end contract management rather than just analysis. The workflow automation handles approvals, redlining, and execution while the AI extracts and tracks key terms.\n\nFor Barnsley businesses that want to streamline their entire contract process - from drafting through negotiation to ongoing management - Ironclad provides the platform to manage contracts as a system rather than as individual documents.',

  // --- E-commerce and retail ---

  nosto:
    "Nosto provides AI-powered product recommendations and personalisation for e-commerce. It analyses user behaviour and purchase patterns to serve personalised product suggestions, content, and experiences.\n\nI use Nosto for e-commerce projects where improving product discovery and average order value matters. The recommendations adapt in real-time based on browsing behaviour, purchase history, and similar customer patterns.\n\nFor Barnsley retailers selling online, Nosto helps customers find products they'll actually want to buy. Personalised recommendations drive higher conversion rates and larger basket sizes without requiring manual merchandising.",

  'algolia-ai':
    "Algolia provides AI-powered search and product discovery for e-commerce and content sites. NeuralSearch combines keyword matching with semantic understanding for search that understands what shoppers mean.\n\nI use Algolia for e-commerce search where speed and relevance directly impact revenue. The AI understands synonyms, typos, and intent, returning relevant results even when queries don't exactly match product titles.\n\nFor Barnsley online retailers, Algolia transforms product search from a frustration into a discovery tool. Customers find what they want faster, even with imprecise searches, which directly improves conversion rates.",

  'dynamic-yield':
    "Dynamic Yield is an AI personalisation platform for e-commerce that customises the entire on-site experience. It personalises product recommendations, content, messaging, and offers based on individual user behaviour.\n\nI use Dynamic Yield for e-commerce projects where personalisation goes beyond just product recommendations - customising landing pages, email content, and promotional offers based on user segments and individual behaviour.\n\nFor Barnsley retailers with online stores, Dynamic Yield makes every visitor's experience more relevant. Returning customers see products and offers based on their history, while new visitors get smart defaults that adapt as they browse.",

  klevu:
    "Klevu provides AI search and merchandising specifically built for e-commerce. It understands product attributes, shopper intent, and merchandising rules to deliver search results that drive sales.\n\nI use Klevu for e-commerce search that needs to balance relevance with merchandising goals. It understands that search isn't just about accuracy - it's about showing products that are available, profitable, and likely to convert.\n\nFor Barnsley online retailers, Klevu improves the search experience while respecting your merchandising strategy. It surfaces relevant products while letting you boost, bury, or pin results based on business priorities.",

  gorgias:
    'Gorgias provides AI-powered customer support specifically for e-commerce, with deep integrations into Shopify, BigCommerce, and other platforms. It automates responses to common queries while pulling order and customer data into the support interface.\n\nI use Gorgias for e-commerce support automation where the AI needs access to order data. It can automatically answer "where\'s my order?" queries by looking up tracking, process returns, and handle common questions without human intervention.\n\nFor Barnsley e-commerce businesses, Gorgias automates the repetitive support queries that eat into your team\'s time. The AI handles order status, returns, and FAQs while your team focuses on complex issues that need a human touch.',

  rebuy:
    'Rebuy provides AI-powered product recommendations and upsells for e-commerce. It uses purchase data and browsing behaviour to suggest complementary products, bundles, and upgrades at key moments in the shopping journey.\n\nI use Rebuy for e-commerce projects focused on increasing average order value. It places intelligent recommendations at checkout, on product pages, and in post-purchase flows based on what actually drives additional purchases.\n\nFor Barnsley online retailers, Rebuy helps maximise the value of every customer visit. AI-driven upsells and cross-sells feel natural to shoppers while meaningfully increasing revenue per order.',

  // --- B2B SaaS and tech ---

  vectara:
    'Vectara provides a conversational search API for SaaS applications. It combines semantic search with generative answers - retrieval that finds the right information and generation that presents it in natural language.\n\nI use Vectara for adding conversational search to products where users expect to ask questions in natural language and get direct answers. It handles the retrieval and generation pipeline in one API.\n\nFor Barnsley SaaS companies wanting to add search or Q&A features to their products, Vectara provides the backend. Users ask questions, Vectara retrieves the relevant information from your data, and returns a grounded answer.',

  'jina-ai':
    'Jina AI provides embeddings, reader tools, and search infrastructure for building RAG and semantic search pipelines. Their reader API extracts clean text from web pages, and their embeddings power semantic matching.\n\nI use Jina AI for the data ingestion and embedding stages of search and RAG pipelines. The reader API handles the messy reality of extracting content from web pages, and the embedding models produce strong representations for semantic search.\n\nFor Barnsley tech companies building search or AI features into their products, Jina AI provides the embedding and ingestion infrastructure. It handles the data preparation so your application can focus on the search experience.',

  // --- Startups and scale-ups ---

  groq: "Groq provides extremely fast LLM inference via custom hardware. The LPU (Language Processing Unit) architecture delivers dramatically lower latency than GPU-based inference, making real-time AI applications more responsive.\n\nI use Groq when latency matters - interactive applications where users are waiting for AI responses and every millisecond counts. The speed difference is noticeable in chat interfaces, real-time analysis, and live processing workflows.\n\nFor Barnsley startups building AI-powered products, Groq provides the inference speed to make AI interactions feel instant. Users don't wait for responses, which makes the difference between AI that feels like a tool and AI that feels like a bottleneck.",

  'mistral-ai':
    "Mistral AI provides open and frontier LLMs with strong performance relative to their size. Their models offer a good balance of capability and cost, with options ranging from small efficient models to large frontier models.\n\nI use Mistral models when a project benefits from the cost-performance trade-off of their model range. The smaller models are efficient enough for high-volume tasks, while the larger models compete with the best for complex reasoning.\n\nFor Barnsley startups building AI products, Mistral provides cost-effective models that perform well. When you're processing high volumes or need to keep inference costs down, Mistral's range lets you pick the right model for each task.",

  // --- Agencies and service providers ---

  jasper:
    "Jasper is an AI content creation platform for marketing teams and agencies. It generates marketing copy, blog posts, social content, and campaign materials with brand voice consistency and style guidelines.\n\nI use Jasper for agency workflows where content production needs to scale across multiple clients while maintaining each client's brand voice. The template system and brand voice features keep output consistent.\n\nFor Barnsley agencies producing content for clients, Jasper accelerates the writing process. It drafts content that matches your client's brand guidelines, which your team then refines. This means more content delivered without proportionally more writing time.",

  'copy-ai':
    'Copy.ai provides AI copywriting for ads, emails, product descriptions, and marketing materials. It generates multiple variations quickly so teams can test and iterate on messaging.\n\nI use Copy.ai for generating copy variations - ad copy, email subject lines, product descriptions - where having multiple options to test and choose from is more valuable than a single perfect draft.\n\nFor Barnsley agencies handling client campaigns, Copy.ai produces draft copy at speed. Your team reviews, selects, and refines the best options rather than starting every piece from scratch.',

  writesonic:
    'Writesonic generates AI-powered copy for landing pages, blog posts, and marketing content. It produces long-form content with SEO awareness, making it useful for content-heavy client deliverables.\n\nI use Writesonic for longer-form content generation - landing pages, blog articles, and content marketing pieces. The SEO features help ensure the content is structured for search visibility from the start.\n\nFor Barnsley agencies delivering content and web copy for clients, Writesonic speeds up the production of landing pages, blog posts, and marketing content. The team focuses on strategy and refinement while the AI handles the first draft.',

  'surfer-seo':
    "Surfer SEO provides AI-powered content optimisation for search engine rankings. It analyses top-ranking content for target keywords and provides guidelines for creating content that competes.\n\nI use Surfer SEO for content projects where organic search performance matters. It takes the guesswork out of content structure - word count, heading structure, keyword density, and topic coverage - based on what's actually ranking.\n\nFor Barnsley agencies managing client SEO, Surfer provides data-driven briefs for content creation. Writers know exactly what to cover and how to structure content to compete for target keywords.",

  frase:
    'Frase combines AI content research with content generation. It analyses the search landscape for a topic, identifies questions people are asking, and helps create content that comprehensively covers the subject.\n\nI use Frase for content strategy and creation where understanding the full topic landscape matters. It shows what questions are being asked, what competitors are covering, and what gaps exist - then helps create content that fills those gaps.\n\nFor Barnsley agencies doing content marketing for clients, Frase provides the research and brief-building that makes content strategy more systematic and content creation more efficient.',

  descript:
    'Descript provides AI-powered video and audio editing with a text-based interface. You edit media by editing the transcript - deleting a sentence removes it from the video, and the AI handles the rest.\n\nI use Descript for video and podcast editing where speed matters more than fine-grained control. Editing by transcript is dramatically faster than traditional timeline editing for content where the words are what matter.\n\nFor Barnsley agencies producing video or audio content for clients, Descript speeds up the editing process. Client testimonials, podcast episodes, and video content get from raw recording to finished deliverable faster.',

  // --- Healthcare and life sciences ---

  'nuance-dax':
    'Nuance DAX is an AI-powered clinical documentation tool that automatically creates notes from patient-clinician conversations. It listens to the encounter and generates structured clinical documentation.\n\nI use Nuance DAX in healthcare AI projects where clinical documentation is a major time burden. The system captures the conversation and produces notes that clinicians review and approve, rather than writing from scratch.\n\nFor Barnsley healthcare providers, DAX reduces the documentation burden that takes clinicians away from patient care. Accurate, structured notes are generated from the conversation, saving time and improving record quality.',

  suki: 'Suki is an AI voice assistant specifically built for clinical documentation. Clinicians dictate notes during or after consultations, and Suki generates structured documentation in the appropriate format.\n\nI use Suki in healthcare settings where voice-driven documentation fits the workflow better than passive ambient listening. Clinicians speak naturally and Suki generates the structured notes.\n\nFor Barnsley healthcare providers who prefer dictation-style documentation, Suki provides AI-powered note generation that understands medical terminology, structures notes correctly, and integrates with clinical systems.',

  abridge:
    "Abridge provides AI-powered documentation of medical conversations. It records clinical encounters and generates structured summaries, capturing the key medical information discussed.\n\nI use Abridge for healthcare documentation projects where capturing the full context of clinical conversations matters. It produces both summaries for quick reference and detailed notes for the medical record.\n\nFor Barnsley healthcare providers, Abridge captures what was discussed in consultations and generates documentation automatically. This reduces note-writing time while ensuring important details aren't missed.",

  tempus:
    'Tempus provides AI for oncology and precision medicine. It analyses clinical and molecular data to help clinicians make treatment decisions informed by genomic insights and real-world evidence.\n\nI use Tempus in healthcare AI projects involving clinical decision support and precision medicine. The platform connects genomic data with clinical outcomes to inform treatment strategies.\n\nFor Barnsley healthcare and life sciences organisations working in oncology or precision medicine, Tempus provides AI-powered insights that connect genomic data with treatment outcomes, supporting more informed clinical decisions.',

  benchsci:
    'BenchSci uses AI to accelerate life sciences research, particularly antibody and reagent discovery. It analyses published experimental data to help researchers find the right reagents and experimental approaches.\n\nI use BenchSci in life sciences AI projects where accelerating the research workflow provides significant value. The platform surfaces relevant experimental data from published literature to inform experimental design.\n\nFor Barnsley life sciences organisations, BenchSci accelerates the research process by using AI to surface relevant experimental evidence and reagent information from the published literature.',

  'semantic-scholar':
    'Semantic Scholar is an AI-powered academic search engine by the Allen Institute for AI. It uses AI to understand and connect research papers, surfacing relevant literature and identifying influential works.\n\nI use Semantic Scholar in healthcare and research AI projects where finding and synthesising relevant literature is part of the workflow. The AI understands paper content and citation networks, making research discovery more efficient.\n\nFor Barnsley healthcare providers and researchers, Semantic Scholar provides AI-powered literature search that finds relevant papers based on meaning rather than just keywords. It surfaces connections and related work that traditional search misses.',

  // --- Logistics and supply chain ---

  fourkites:
    'FourKites provides real-time supply chain visibility and predictive ETAs. It connects carriers, shippers, and receivers with live tracking and AI-predicted arrival times.\n\nI use FourKites in logistics AI projects where shipment visibility and accurate delivery predictions matter. The platform aggregates tracking data across carriers and applies AI to predict delays and estimate arrivals.\n\nFor Barnsley logistics businesses, FourKites provides the visibility layer that lets you track shipments in real-time and predict delivery times accurately. This means fewer "where\'s my delivery?" calls and better planning for receiving teams.',

  project44:
    'Project44 provides supply chain visibility and logistics intelligence. It connects shippers with carrier networks and provides real-time tracking, analytics, and exception management across the supply chain.\n\nI use Project44 for logistics projects needing multi-carrier visibility and analytics. It aggregates shipment data across carriers and provides intelligence on exceptions, delays, and performance patterns.\n\nFor Barnsley businesses shipping or receiving goods, Project44 provides a unified view of shipments across different carriers. The analytics help identify patterns in delays, costs, and carrier performance.',

  flexport:
    'Flexport provides AI-powered freight forwarding and customs automation. It handles international shipping, customs documentation, and supply chain coordination with technology that reduces manual work.\n\nI use Flexport in logistics projects involving international shipping where customs and freight complexity create manual work. The platform automates documentation, booking, and coordination.\n\nFor Barnsley businesses involved in import/export, Flexport automates the freight and customs processes that otherwise require significant manual coordination. It handles the complexity of international logistics with AI-assisted documentation and booking.',

  'blue-yonder':
    'Blue Yonder provides AI for demand planning and supply chain optimisation. It forecasts demand, optimises inventory levels, and coordinates supply chain planning across the network.\n\nI use Blue Yonder for supply chain projects where demand forecasting and inventory optimisation have significant financial impact. The AI analyses historical patterns, external signals, and supply constraints to produce actionable plans.\n\nFor Barnsley businesses managing inventory and supply chains, Blue Yonder provides AI-powered demand forecasting that reduces both stockouts and excess inventory. Better forecasts mean better purchasing decisions and less waste.',

  locus:
    'Locus provides AI-powered route optimisation for last-mile delivery. It calculates efficient delivery routes considering constraints like time windows, vehicle capacity, driver schedules, and real-time traffic.\n\nI use Locus for delivery and field service projects where route efficiency directly impacts costs and customer satisfaction. The AI optimises across multiple constraints simultaneously, finding routes that humans would take much longer to plan.\n\nFor Barnsley delivery and field service businesses, Locus optimises driver routes to reduce mileage, improve on-time delivery, and fit more deliveries into each day. Better routing means lower costs and happier customers.',

  kinaxis:
    'Kinaxis provides AI for supply chain planning and demand sensing. It combines planning, analytics, and scenario modelling to help businesses respond to supply chain changes and disruptions.\n\nI use Kinaxis in supply chain projects where planning agility matters - businesses that need to sense demand changes quickly and adjust plans across procurement, production, and distribution.\n\nFor Barnsley manufacturers and distributors, Kinaxis provides the planning intelligence to respond to supply chain changes before they become problems. It senses demand shifts and helps you adjust procurement and production plans accordingly.',

  // --- Education and training ---

  'khan-academy':
    "Khan Academy uses AI through Khanmigo to provide personalised tutoring and learning support. The AI tutor adapts to each learner's level, provides hints rather than answers, and guides students through problem-solving.\n\nI reference Khan Academy's approach in education AI projects because Khanmigo demonstrates how AI tutoring should work - supporting learning rather than replacing it. The system guides students to understanding rather than just giving them answers.\n\nFor Barnsley education providers, Khan Academy's AI tutoring model shows what's possible for personalised learning support. The approach of AI as a patient, adaptive tutor that scaffolds understanding is the standard for educational AI.",

  duolingo:
    "Duolingo uses AI to adapt language learning to each user's level and goals. The AI adjusts difficulty, spacing, and content based on performance, ensuring learners are consistently challenged without being overwhelmed.\n\nI reference Duolingo's adaptive learning approach in education AI projects. Their AI-driven personalisation - adjusting content difficulty, review timing, and exercise types based on individual performance - is a model for how educational AI should adapt.\n\nFor Barnsley education and training providers, Duolingo demonstrates how AI can personalise learning paths at scale. The same principles - adaptive difficulty, spaced repetition, and performance-based content selection - apply to any training content.",

  grammarly:
    'Grammarly provides AI-powered writing assistance with grammar correction, style suggestions, and clarity improvements. It works across applications and provides real-time feedback as users write.\n\nI reference Grammarly in education AI projects as an example of AI that supports skill development rather than replacing it. Users learn to write better through consistent, contextual feedback.\n\nFor Barnsley education providers, Grammarly-style AI feedback helps learners improve their writing through practice with real-time guidance. The AI catches errors and suggests improvements while the learner develops their own skills.',

  quizlet:
    "Quizlet provides AI-powered study tools including flashcard generation, practice tests, and adaptive study modes. The AI generates study materials from content and adapts practice sessions based on what the learner knows and doesn't know.\n\nI reference Quizlet in education AI projects for its approach to AI-generated study materials and adaptive practice. The system identifies knowledge gaps and focuses practice where it's needed most.\n\nFor Barnsley training providers, Quizlet's approach demonstrates how AI can generate assessments, identify gaps, and focus practice time efficiently. The same principles apply to professional training and compliance learning.",

  coursera:
    'Coursera uses AI for course recommendations and personalised learning paths. It analyses learner behaviour, skills, and goals to suggest relevant courses and structure learning journeys.\n\nI reference Coursera in education AI projects for their recommendation and learning path systems. The AI connects what a learner knows with what they need to learn and suggests the most efficient path.\n\nFor Barnsley education and training organisations, Coursera demonstrates how AI can map learning paths and recommend content based on individual goals and existing knowledge. This personalisation approach works for any structured learning content.',
}
