import { C, escapeHtml, sendReportAndLead } from '@/lib/email'
import { siteUrl } from '@/lib/siteConfig'

function buildEmailHtml({ sections, checklist, permalink }) {
  const sectionsHtml = sections
    .map(
      (s) =>
        `<div style="margin-bottom: 20px;">
          <h3 style="font-size: 11px; font-weight: bold; text-transform: uppercase; letter-spacing: 0.5px; color: #a1a1aa; margin: 0 0 6px;">${escapeHtml(s.label)}</h3>
          <p style="color: ${C.HEADING}; font-size: 14px; line-height: 1.6; margin: 0;">${escapeHtml(s.value)}</p>
        </div>`,
    )
    .join('')

  return `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
      <h2 style="color: ${C.HEADING}; border-bottom: 2px solid ${C.TEAL}; padding-bottom: 10px;">
        Your AI PoC Scope Document
      </h2>

      <div style="background: #f0fdfa; border: 2px solid ${C.TEAL}; border-radius: 12px; padding: 24px; margin: 20px 0;">
        ${sectionsHtml}
      </div>

      <div style="margin-top: 24px;">
        <h3 style="color: ${C.SUBHEADING}; margin: 0 0 12px;">What to do next</h3>
        <table style="width: 100%; border-collapse: collapse;">
          ${(checklist || [])
            .map(
              (item, i) => `<tr>
            <td style="padding: 8px 12px; vertical-align: top;">
              <span style="display: inline-block; width: 24px; height: 24px; line-height: 24px; text-align: center; border-radius: 50%; background: ${i === 0 ? C.TEAL : '#d4d4d8'}; color: ${i === 0 ? '#fff' : '#52525b'}; font-size: 12px; font-weight: bold;">${i + 1}</span>
            </td>
            <td style="padding: 8px 12px; color: ${C.TEXT}; font-size: 14px; line-height: 1.5;">${item}</td>
          </tr>`,
            )
            .join('')}
        </table>
      </div>

      <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid ${C.BORDER}; color: ${C.TEXT}; font-size: 13px;">
        <p>This report was generated by the <a href="${permalink || siteUrl + '/projects/tools/ai-poc-scope-template'}" style="color: ${C.TEAL};">AI PoC Scope Template</a> tool on mitchellbryson.com.</p>
        <p>Want to discuss your results? <a href="${siteUrl}/contact" style="color: ${C.TEAL};">Get in touch</a>.</p>
      </div>
    </div>
  `
}

export async function POST(request) {
  const { email, toolName, permalink, sections, checklist } =
    await request.json()

  return sendReportAndLead({
    email,
    toolName,
    permalink,
    subject: 'Your AI PoC Scope Document',
    html: buildEmailHtml({ sections, checklist, permalink }),
    leadSummaryHtml: sections
      .map(
        (s) =>
          `<p><strong>${escapeHtml(s.label)}:</strong> ${escapeHtml(s.value)}</p>`,
      )
      .join(''),
  })
}
