import { Resend } from 'resend'
import { NextResponse } from 'next/server'

let resend = null
function getResend() {
  if (!resend) {
    resend = new Resend(process.env.RESEND_API_KEY)
  }
  return resend
}

const C = {
  TEAL: '#14b8a6',
  HEADING: '#333',
  SUBHEADING: '#555',
  TEXT: '#666',
  BG: '#f8f9fa',
  BORDER: '#e9ecef',
}

function buildEmailHtml({ results, suggestedTools, permalink }) {
  const cardsHtml = results
    .map(
      (r, i) =>
        `<div style="background: ${i === 0 ? '#f0fdfa' : C.BG}; border: ${i === 0 ? '2px solid ' + C.TEAL : '1px solid ' + C.BORDER}; border-radius: 12px; padding: 20px; margin-bottom: 16px;">
          <p style="font-size: 11px; font-weight: bold; text-transform: uppercase; letter-spacing: 0.5px; color: ${i === 0 ? '#0d9488' : '#a1a1aa'}; margin: 0 0 8px;">${r.category}</p>
          <h3 style="color: ${C.HEADING}; margin: 0 0 4px; font-size: 16px;">${r.name}</h3>
          <p style="color: ${C.TEXT}; font-size: 13px; line-height: 1.5; margin: 0 0 10px;">${r.description}</p>
          <div style="background: ${i === 0 ? '#fff' : '#fff'}; border-radius: 6px; padding: 10px 14px;">
            <p style="font-size: 11px; font-weight: bold; color: #a1a1aa; margin: 0 0 4px;">Why this choice</p>
            <p style="color: ${C.TEXT}; font-size: 13px; line-height: 1.5; margin: 0;">${r.rationale}</p>
          </div>
        </div>`,
    )
    .join('')

  return `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
      <h2 style="color: ${C.HEADING}; border-bottom: 2px solid ${C.TEAL}; padding-bottom: 10px;">
        Your RAG Architecture Recommendation
      </h2>

      ${cardsHtml}

      <div style="margin-top: 24px;">
        <h3 style="color: ${C.SUBHEADING}; margin: 0 0 12px;">Next steps</h3>
        <table style="width: 100%; border-collapse: collapse;">
          <tr>
            <td style="padding: 8px 12px; vertical-align: top;">
              <span style="display: inline-block; width: 24px; height: 24px; line-height: 24px; text-align: center; border-radius: 50%; background: ${C.TEAL}; color: #fff; font-size: 12px; font-weight: bold;">1</span>
            </td>
            <td style="padding: 8px 12px; color: ${C.TEXT}; font-size: 14px; line-height: 1.5;">Set up your vector database and test with a sample dataset</td>
          </tr>
          <tr>
            <td style="padding: 8px 12px; vertical-align: top;">
              <span style="display: inline-block; width: 24px; height: 24px; line-height: 24px; text-align: center; border-radius: 50%; background: #d4d4d8; color: #52525b; font-size: 12px; font-weight: bold;">2</span>
            </td>
            <td style="padding: 8px 12px; color: ${C.TEXT}; font-size: 14px; line-height: 1.5;">Experiment with chunking strategies on your actual content</td>
          </tr>
          <tr>
            <td style="padding: 8px 12px; vertical-align: top;">
              <span style="display: inline-block; width: 24px; height: 24px; line-height: 24px; text-align: center; border-radius: 50%; background: #d4d4d8; color: #52525b; font-size: 12px; font-weight: bold;">3</span>
            </td>
            <td style="padding: 8px 12px; color: ${C.TEXT}; font-size: 14px; line-height: 1.5;">Measure retrieval quality before adding reranking</td>
          </tr>
        </table>
      </div>

      ${suggestedTools && suggestedTools.length > 0 ? `
      <div style="margin-top: 24px;">
        <h3 style="color: ${C.SUBHEADING}; margin: 0 0 12px;">Explore further</h3>
        ${suggestedTools.map((t) => `<div style="background: ${C.BG}; border-radius: 8px; padding: 12px 16px; margin-bottom: 8px;">
          <a href="https://mitchellbryson.com${t.href}" style="color: ${C.TEAL}; font-size: 14px; font-weight: bold; text-decoration: none;">${t.name}</a>
          <p style="color: ${C.TEXT}; font-size: 13px; line-height: 1.4; margin: 4px 0 0;">${t.description}</p>
        </div>`).join('')}
      </div>
      ` : ''}

      <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid ${C.BORDER}; color: ${C.TEXT}; font-size: 13px;">
        <p>This report was generated by the <a href="${permalink || 'https://mitchellbryson.com/projects/tools/rag-decision-tree'}" style="color: ${C.TEAL};">RAG Architecture Decision Tree</a> tool on mitchellbryson.com.</p>
        <p>Want to discuss your results? <a href="https://mitchellbryson.com/contact" style="color: ${C.TEAL};">Get in touch</a>.</p>
      </div>
    </div>
  `
}

export async function POST(request) {
  try {
    const { email, toolName, permalink, results, suggestedTools, answers } = await request.json()

    if (!email) {
      return NextResponse.json({ error: 'Email is required' }, { status: 400 })
    }

    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
    if (!emailRegex.test(email)) {
      return NextResponse.json({ error: 'Invalid email address' }, { status: 400 })
    }

    const r = getResend()

    const vectorDb = results[0]?.name || 'your stack'
    const embedding = results[1]?.name || ''

    const { error } = await r.emails.send({
      from: `Mitchell Bryson <${process.env.CONTACT_EMAIL}>`,
      to: [email],
      subject: `Your RAG Architecture: ${vectorDb} + ${embedding}`,
      html: buildEmailHtml({ results, suggestedTools, permalink }),
    })

    if (error) {
      console.error('Resend error (RAG report):', error)
      return NextResponse.json({ error: 'Failed to send report' }, { status: 500 })
    }

    await r.emails.send({
      from: `Website <${process.env.CONTACT_EMAIL}>`,
      to: [process.env.CONTACT_EMAIL],
      subject: `${toolName}: new lead from ${email}`,
      replyTo: email,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h2 style="color: ${C.HEADING}; border-bottom: 2px solid ${C.TEAL}; padding-bottom: 10px;">
            New ${toolName} Lead
          </h2>
          <div style="background: ${C.BG}; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <p><strong>Email:</strong> ${email}</p>
            <p><strong>Tool:</strong> ${toolName}</p>
            <p><strong>Stack:</strong> ${results.map((r) => r.name).join(', ')}</p>
            <p><strong>Results:</strong> <a href="${permalink}" style="color: ${C.TEAL};">${permalink}</a></p>
          </div>
          <p style="color: ${C.TEXT}; font-size: 14px;">Reply directly to this email to reach them.</p>
        </div>
      `,
    })

    return NextResponse.json({ message: 'Report sent successfully' }, { status: 200 })
  } catch (error) {
    console.error('API error:', error)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}
