import { C, sendReportAndLead } from '@/lib/email'
import { siteUrl } from '@/lib/siteConfig'

function buildEmailHtml({ results, suggestedTools, permalink }) {
  const cardsHtml = results
    .map(
      (r, i) =>
        `<div style="background: ${i === 0 ? '#f0fdfa' : C.BG}; border: ${i === 0 ? '2px solid ' + C.TEAL : '1px solid ' + C.BORDER}; border-radius: 12px; padding: 20px; margin-bottom: 16px;">
          <p style="font-size: 11px; font-weight: bold; text-transform: uppercase; letter-spacing: 0.5px; color: ${i === 0 ? '#0d9488' : '#a1a1aa'}; margin: 0 0 8px;">${r.category}</p>
          <h3 style="color: ${C.HEADING}; margin: 0 0 4px; font-size: 16px;">${r.name}</h3>
          <p style="color: ${C.TEXT}; font-size: 13px; line-height: 1.5; margin: 0 0 10px;">${r.description}</p>
          <div style="background: #fff; border-radius: 6px; padding: 10px 14px;">
            <p style="font-size: 11px; font-weight: bold; color: #a1a1aa; margin: 0 0 4px;">Why this choice</p>
            <p style="color: ${C.TEXT}; font-size: 13px; line-height: 1.5; margin: 0;">${r.rationale}</p>
          </div>
        </div>`,
    )
    .join('')

  return `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
      <h2 style="color: ${C.HEADING}; border-bottom: 2px solid ${C.TEAL}; padding-bottom: 10px;">
        Your RAG Architecture Recommendation
      </h2>

      ${cardsHtml}

      <div style="margin-top: 24px;">
        <h3 style="color: ${C.SUBHEADING}; margin: 0 0 12px;">Next steps</h3>
        <table style="width: 100%; border-collapse: collapse;">
          <tr>
            <td style="padding: 8px 12px; vertical-align: top;">
              <span style="display: inline-block; width: 24px; height: 24px; line-height: 24px; text-align: center; border-radius: 50%; background: ${C.TEAL}; color: #fff; font-size: 12px; font-weight: bold;">1</span>
            </td>
            <td style="padding: 8px 12px; color: ${C.TEXT}; font-size: 14px; line-height: 1.5;">Set up your vector database and test with a sample dataset</td>
          </tr>
          <tr>
            <td style="padding: 8px 12px; vertical-align: top;">
              <span style="display: inline-block; width: 24px; height: 24px; line-height: 24px; text-align: center; border-radius: 50%; background: #d4d4d8; color: #52525b; font-size: 12px; font-weight: bold;">2</span>
            </td>
            <td style="padding: 8px 12px; color: ${C.TEXT}; font-size: 14px; line-height: 1.5;">Experiment with chunking strategies on your actual content</td>
          </tr>
          <tr>
            <td style="padding: 8px 12px; vertical-align: top;">
              <span style="display: inline-block; width: 24px; height: 24px; line-height: 24px; text-align: center; border-radius: 50%; background: #d4d4d8; color: #52525b; font-size: 12px; font-weight: bold;">3</span>
            </td>
            <td style="padding: 8px 12px; color: ${C.TEXT}; font-size: 14px; line-height: 1.5;">Measure retrieval quality before adding reranking</td>
          </tr>
        </table>
      </div>

      ${
        suggestedTools && suggestedTools.length > 0
          ? `
      <div style="margin-top: 24px;">
        <h3 style="color: ${C.SUBHEADING}; margin: 0 0 12px;">Explore further</h3>
        ${suggestedTools
          .map(
            (
              t,
            ) => `<div style="background: ${C.BG}; border-radius: 8px; padding: 12px 16px; margin-bottom: 8px;">
          <a href="${siteUrl}${t.href}" style="color: ${C.TEAL}; font-size: 14px; font-weight: bold; text-decoration: none;">${t.name}</a>
          <p style="color: ${C.TEXT}; font-size: 13px; line-height: 1.4; margin: 4px 0 0;">${t.description}</p>
        </div>`,
          )
          .join('')}
      </div>
      `
          : ''
      }

      <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid ${C.BORDER}; color: ${C.TEXT}; font-size: 13px;">
        <p>This report was generated by the <a href="${permalink || siteUrl + '/projects/tools/rag-decision-tree'}" style="color: ${C.TEAL};">RAG Architecture Decision Tree</a> tool on mitchellbryson.com.</p>
        <p>Want to discuss your results? <a href="${siteUrl}/contact" style="color: ${C.TEAL};">Get in touch</a>.</p>
      </div>
    </div>
  `
}

export async function POST(request) {
  const { email, toolName, permalink, results, suggestedTools } =
    await request.json()

  const vectorDb = results[0]?.name || 'your stack'
  const embedding = results[1]?.name || ''

  return sendReportAndLead({
    email,
    toolName,
    permalink,
    subject: `Your RAG Architecture: ${vectorDb} + ${embedding}`,
    html: buildEmailHtml({ results, suggestedTools, permalink }),
    leadSummaryHtml: `<p><strong>Stack:</strong> ${results.map((r) => r.name).join(', ')}</p>`,
  })
}
