import { Resend } from 'resend'
import { NextResponse } from 'next/server'

let resend = null
function getResend() {
  if (!resend) {
    resend = new Resend(process.env.RESEND_API_KEY)
  }
  return resend
}

const C = {
  TEAL: '#14b8a6',
  HEADING: '#333',
  SUBHEADING: '#555',
  TEXT: '#666',
  BG: '#f8f9fa',
  BORDER: '#e9ecef',
}

function buildDiagramHtml(results) {
  return results
    .map((r, i) => {
      const isFirst = i === 0
      const boxBorder = isFirst ? `2px solid ${C.TEAL}` : `1px solid ${C.BORDER}`
      const boxBg = isFirst ? '#f0fdfa' : C.BG
      const labelColor = isFirst ? '#0d9488' : '#a1a1aa'

      const box = `<tr>
        <td style="text-align: center; padding: 0;">
          <div style="display: inline-block; border: ${boxBorder}; border-radius: 10px; padding: 10px 32px; background: ${boxBg};">
            <div style="font-size: 10px; font-weight: bold; text-transform: uppercase; letter-spacing: 0.5px; color: ${labelColor}; margin: 0;">${r.category}</div>
            <div style="font-size: 15px; font-weight: bold; color: ${C.HEADING}; margin-top: 2px;">${r.name}</div>
          </div>
        </td>
      </tr>`

      const arrow =
        i < results.length - 1
          ? `<tr><td style="text-align: center; padding: 2px 0; font-size: 16px; color: #d4d4d8; line-height: 1;">&#9660;</td></tr>`
          : ''

      return box + arrow
    })
    .join('')
}

function buildEmailHtml({ results, permalink }) {
  const cardsHtml = results
    .map(
      (r) => {
        const siteLinkHtml = r.siteLink
          ? `<a href="https://mitchellbryson.com${r.siteLink}" style="color: ${C.TEAL}; font-size: 13px; font-weight: bold; text-decoration: none; margin-right: 16px;">How I use it &rarr;</a>`
          : ''
        const docsLinkHtml = r.docs
          ? `<a href="${r.docs}" style="color: #a1a1aa; font-size: 13px; font-weight: bold; text-decoration: none;">Docs &rarr;</a>`
          : ''
        return `<div style="background: ${C.BG}; border: 1px solid ${C.BORDER}; border-radius: 12px; padding: 16px 20px; margin-bottom: 12px;">
          <p style="font-size: 11px; font-weight: bold; text-transform: uppercase; letter-spacing: 0.5px; color: #0d9488; margin: 0 0 6px;">${r.category}</p>
          <h3 style="color: ${C.HEADING}; margin: 0 0 4px; font-size: 16px;">${r.name}</h3>
          <p style="color: ${C.TEXT}; font-size: 13px; line-height: 1.5; margin: 0 0 8px;">${r.rationale}</p>
          ${siteLinkHtml}${docsLinkHtml}
        </div>`
      },
    )
    .join('')

  const diagramHtml = buildDiagramHtml(results)

  return `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
      <h2 style="color: ${C.HEADING}; border-bottom: 2px solid ${C.TEAL}; padding-bottom: 10px;">
        Your Recommended Tech Stack
      </h2>

      <table style="width: 100%; border-collapse: collapse; margin: 24px 0;">
        <tbody>${diagramHtml}</tbody>
      </table>

      ${cardsHtml}

      <div style="margin-top: 24px;">
        <h3 style="color: ${C.SUBHEADING}; margin: 0 0 12px;">Next steps</h3>
        <table style="width: 100%; border-collapse: collapse;">
          <tr>
            <td style="padding: 8px 12px; vertical-align: top;">
              <span style="display: inline-block; width: 24px; height: 24px; line-height: 24px; text-align: center; border-radius: 50%; background: ${C.TEAL}; color: #fff; font-size: 12px; font-weight: bold;">1</span>
            </td>
            <td style="padding: 8px 12px; color: ${C.TEXT}; font-size: 14px; line-height: 1.5;">Review the docs for each recommended technology</td>
          </tr>
          <tr>
            <td style="padding: 8px 12px; vertical-align: top;">
              <span style="display: inline-block; width: 24px; height: 24px; line-height: 24px; text-align: center; border-radius: 50%; background: #d4d4d8; color: #52525b; font-size: 12px; font-weight: bold;">2</span>
            </td>
            <td style="padding: 8px 12px; color: ${C.TEXT}; font-size: 14px; line-height: 1.5;">Scaffold a small proof of concept to validate the stack</td>
          </tr>
          <tr>
            <td style="padding: 8px 12px; vertical-align: top;">
              <span style="display: inline-block; width: 24px; height: 24px; line-height: 24px; text-align: center; border-radius: 50%; background: #d4d4d8; color: #52525b; font-size: 12px; font-weight: bold;">3</span>
            </td>
            <td style="padding: 8px 12px; color: ${C.TEXT}; font-size: 14px; line-height: 1.5;">Get in touch if you want help building with this stack</td>
          </tr>
        </table>
      </div>

      <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid ${C.BORDER}; color: ${C.TEXT}; font-size: 13px;">
        <p>This report was generated by the <a href="${permalink || 'https://mitchellbryson.com/projects/tools/tech-stack-picker'}" style="color: ${C.TEAL};">Tech Stack Picker</a> tool on mitchellbryson.com.</p>
        <p>Want to discuss your results? <a href="https://mitchellbryson.com/contact" style="color: ${C.TEAL};">Get in touch</a>.</p>
      </div>
    </div>
  `
}

export async function POST(request) {
  try {
    const { email, toolName, permalink, results, answers } = await request.json()

    if (!email) {
      return NextResponse.json({ error: 'Email is required' }, { status: 400 })
    }

    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
    if (!emailRegex.test(email)) {
      return NextResponse.json({ error: 'Invalid email address' }, { status: 400 })
    }

    const r = getResend()

    const { error } = await r.emails.send({
      from: `Mitchell Bryson <${process.env.CONTACT_EMAIL}>`,
      to: [email],
      subject: 'Your Recommended Tech Stack',
      html: buildEmailHtml({ results, permalink }),
    })

    if (error) {
      console.error('Resend error (stack report):', error)
      return NextResponse.json({ error: 'Failed to send report' }, { status: 500 })
    }

    await r.emails.send({
      from: `Website <${process.env.CONTACT_EMAIL}>`,
      to: [process.env.CONTACT_EMAIL],
      subject: `${toolName}: new lead from ${email}`,
      replyTo: email,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h2 style="color: ${C.HEADING}; border-bottom: 2px solid ${C.TEAL}; padding-bottom: 10px;">
            New ${toolName} Lead
          </h2>
          <div style="background: ${C.BG}; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <p><strong>Email:</strong> ${email}</p>
            <p><strong>Tool:</strong> ${toolName}</p>
            <p><strong>Stack:</strong> ${results.map((r) => r.name).join(', ')}</p>
            <p><strong>Results:</strong> <a href="${permalink}" style="color: ${C.TEAL};">${permalink}</a></p>
          </div>
          <p style="color: ${C.TEXT}; font-size: 14px;">Reply directly to this email to reach them.</p>
        </div>
      `,
    })

    return NextResponse.json({ message: 'Report sent successfully' }, { status: 200 })
  } catch (error) {
    console.error('API error:', error)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}
