import { C, sendReportAndLead } from '@/lib/email'

function buildEmailHtml({
  winner,
  primary,
  allEstimates,
  suggestedTools,
  permalink,
}) {
  const all = ['build', 'buy', 'ai']

  const comparisonRows = ['Cost', 'Timeline', 'Maintenance']
    .map((label, i) => {
      const key = ['cost', 'timeline', 'maintenance'][i]
      return `<tr style="border-bottom: 1px solid ${C.BORDER};">
        <td style="padding: 10px 12px; font-weight: bold; color: ${C.SUBHEADING};">${label}</td>
        ${all
          .map(
            (k) =>
              `<td style="padding: 10px 12px; color: ${k === winner ? '#0d9488' : C.TEXT};">${allEstimates[k].estimates[key]}</td>`,
          )
          .join('')}
      </tr>`
    })
    .join('')

  return `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
      <h2 style="color: ${C.HEADING}; border-bottom: 2px solid ${C.TEAL}; padding-bottom: 10px;">
        Your Build vs Buy vs AI Recommendation
      </h2>

      <div style="background: #f0fdfa; border: 2px solid ${C.TEAL}; border-radius: 12px; padding: 20px; margin: 20px 0;">
        <p style="font-size: 11px; font-weight: bold; text-transform: uppercase; letter-spacing: 0.5px; color: #0d9488; margin: 0 0 8px;">Our recommendation</p>
        <h3 style="color: ${C.HEADING}; margin: 0 0 8px; font-size: 18px;">${allEstimates[winner].label}</h3>
        <p style="color: ${C.TEXT}; font-size: 14px; line-height: 1.6; margin: 0;">${primary.summary}</p>
      </div>

      <table style="width: 100%; border-collapse: collapse; font-size: 13px; margin: 20px 0;">
        <thead>
          <tr style="border-bottom: 2px solid ${C.BORDER};">
            <th style="padding: 8px 12px; text-align: left; color: ${C.SUBHEADING};"></th>
            ${all
              .map(
                (k) =>
                  `<th style="padding: 8px 12px; text-align: left; color: ${k === winner ? '#0d9488' : C.HEADING}; font-weight: bold;">${allEstimates[k].label}</th>`,
              )
              .join('')}
          </tr>
        </thead>
        <tbody>
          ${comparisonRows}
        </tbody>
      </table>

      ${
        suggestedTools && suggestedTools.length > 0
          ? `
      <div style="margin-top: 24px;">
        <h3 style="color: ${C.SUBHEADING}; margin: 0 0 12px;">Useful tools for this approach</h3>
        ${suggestedTools
          .map(
            (
              t,
            ) => `<div style="background: ${C.BG}; border-radius: 8px; padding: 12px 16px; margin-bottom: 8px;">
          <a href="https://mitchellbryson.com${t.href}" style="color: ${C.TEAL}; font-size: 14px; font-weight: bold; text-decoration: none;">${t.name}</a>
          <p style="color: ${C.TEXT}; font-size: 13px; line-height: 1.4; margin: 4px 0 0;">${t.description}</p>
        </div>`,
          )
          .join('')}
      </div>
      `
          : ''
      }

      <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid ${C.BORDER}; color: ${C.TEXT}; font-size: 13px;">
        <p>This report was generated by the <a href="${permalink || 'https://mitchellbryson.com/projects/tools/build-vs-buy-vs-ai'}" style="color: ${C.TEAL};">Build vs Buy vs AI</a> tool on mitchellbryson.com.</p>
        <p>Want to discuss your results? <a href="https://mitchellbryson.com/contact" style="color: ${C.TEAL};">Get in touch</a>.</p>
      </div>
    </div>
  `
}

export async function POST(request) {
  const {
    email,
    toolName,
    permalink,
    winner,
    primary,
    allEstimates,
    suggestedTools,
  } = await request.json()

  return sendReportAndLead({
    email,
    toolName,
    permalink,
    subject: `Your Build vs Buy vs AI Recommendation: ${primary.label}`,
    html: buildEmailHtml({
      winner,
      primary,
      allEstimates,
      suggestedTools,
      permalink,
    }),
    leadSummaryHtml: `<p><strong>Recommended:</strong> ${primary.label}</p>`,
  })
}
