import { Resend } from 'resend'
import { NextResponse } from 'next/server'

let resend = null
function getResend() {
  if (!resend) {
    resend = new Resend(process.env.RESEND_API_KEY)
  }
  return resend
}

const C = {
  TEAL: '#14b8a6',
  HEADING: '#333',
  SUBHEADING: '#555',
  TEXT: '#666',
  BG: '#f8f9fa',
  BORDER: '#e9ecef',
}

const RECOMMENDATIONS = {
  build: {
    label: 'Build it yourself',
    summary: 'Your needs are complex enough and strategic enough that building a custom solution gives you the most control and long-term value.',
    estimates: { cost: '\u00a320k-100k+', timeline: '3-9 months', maintenance: 'Ongoing internal team or retainer' },
  },
  buy: {
    label: 'Buy off-the-shelf',
    summary: 'An existing product covers your needs well. Buying saves time and lets you focus your resources on your core business.',
    estimates: { cost: '\u00a3100-2,000/month', timeline: 'Days to weeks', maintenance: 'Vendor-managed with subscription' },
  },
  ai: {
    label: 'Build with AI',
    summary: 'Your problem is a strong fit for AI. An AI-powered solution can deliver capabilities that traditional software cannot.',
    estimates: { cost: '\u00a310k-50k build + API costs', timeline: '4-12 weeks for PoC', maintenance: 'Model monitoring + API costs' },
  },
}

function buildEmailHtml({ winner, primary, suggestedTools, scores, permalink }) {
  const rec = RECOMMENDATIONS[winner]
  const all = ['build', 'buy', 'ai']

  const comparisonRows = ['Cost', 'Timeline', 'Maintenance']
    .map((label, i) => {
      const key = ['cost', 'timeline', 'maintenance'][i]
      return `<tr style="border-bottom: 1px solid ${C.BORDER};">
        <td style="padding: 10px 12px; font-weight: bold; color: ${C.SUBHEADING};">${label}</td>
        ${all
          .map(
            (k) =>
              `<td style="padding: 10px 12px; color: ${k === winner ? '#0d9488' : C.TEXT};">${RECOMMENDATIONS[k].estimates[key]}</td>`,
          )
          .join('')}
      </tr>`
    })
    .join('')

  return `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
      <h2 style="color: ${C.HEADING}; border-bottom: 2px solid ${C.TEAL}; padding-bottom: 10px;">
        Your Build vs Buy vs AI Recommendation
      </h2>

      <div style="background: #f0fdfa; border: 2px solid ${C.TEAL}; border-radius: 12px; padding: 20px; margin: 20px 0;">
        <p style="font-size: 11px; font-weight: bold; text-transform: uppercase; letter-spacing: 0.5px; color: #0d9488; margin: 0 0 8px;">Our recommendation</p>
        <h3 style="color: ${C.HEADING}; margin: 0 0 8px; font-size: 18px;">${rec.label}</h3>
        <p style="color: ${C.TEXT}; font-size: 14px; line-height: 1.6; margin: 0;">${primary.summary}</p>
      </div>

      <table style="width: 100%; border-collapse: collapse; font-size: 13px; margin: 20px 0;">
        <thead>
          <tr style="border-bottom: 2px solid ${C.BORDER};">
            <th style="padding: 8px 12px; text-align: left; color: ${C.SUBHEADING};"></th>
            ${all
              .map(
                (k) =>
                  `<th style="padding: 8px 12px; text-align: left; color: ${k === winner ? '#0d9488' : C.HEADING}; font-weight: bold;">${RECOMMENDATIONS[k].label}</th>`,
              )
              .join('')}
          </tr>
        </thead>
        <tbody>
          ${comparisonRows}
        </tbody>
      </table>

      ${suggestedTools && suggestedTools.length > 0 ? `
      <div style="margin-top: 24px;">
        <h3 style="color: ${C.SUBHEADING}; margin: 0 0 12px;">Useful tools for this approach</h3>
        ${suggestedTools.map((t) => `<div style="background: ${C.BG}; border-radius: 8px; padding: 12px 16px; margin-bottom: 8px;">
          <a href="https://mitchellbryson.com${t.href}" style="color: ${C.TEAL}; font-size: 14px; font-weight: bold; text-decoration: none;">${t.name}</a>
          <p style="color: ${C.TEXT}; font-size: 13px; line-height: 1.4; margin: 4px 0 0;">${t.description}</p>
        </div>`).join('')}
      </div>
      ` : ''}

      <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid ${C.BORDER}; color: ${C.TEXT}; font-size: 13px;">
        <p>This report was generated by the <a href="${permalink || 'https://mitchellbryson.com/projects/tools/build-vs-buy-vs-ai'}" style="color: ${C.TEAL};">Build vs Buy vs AI</a> tool on mitchellbryson.com.</p>
        <p>Want to discuss your results? <a href="https://mitchellbryson.com/contact" style="color: ${C.TEAL};">Get in touch</a>.</p>
      </div>
    </div>
  `
}

export async function POST(request) {
  try {
    const { email, toolName, permalink, winner, primary, suggestedTools, scores, answers } =
      await request.json()

    if (!email) {
      return NextResponse.json({ error: 'Email is required' }, { status: 400 })
    }

    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
    if (!emailRegex.test(email)) {
      return NextResponse.json({ error: 'Invalid email address' }, { status: 400 })
    }

    const r = getResend()

    const { error } = await r.emails.send({
      from: `Mitchell Bryson <${process.env.CONTACT_EMAIL}>`,
      to: [email],
      subject: `Your Build vs Buy vs AI Recommendation: ${primary.label}`,
      html: buildEmailHtml({ winner, primary, suggestedTools, scores, permalink }),
    })

    if (error) {
      console.error('Resend error (build-buy report):', error)
      return NextResponse.json({ error: 'Failed to send report' }, { status: 500 })
    }

    await r.emails.send({
      from: `Website <${process.env.CONTACT_EMAIL}>`,
      to: [process.env.CONTACT_EMAIL],
      subject: `${toolName}: new lead from ${email}`,
      replyTo: email,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h2 style="color: ${C.HEADING}; border-bottom: 2px solid ${C.TEAL}; padding-bottom: 10px;">
            New ${toolName} Lead
          </h2>
          <div style="background: ${C.BG}; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <p><strong>Email:</strong> ${email}</p>
            <p><strong>Tool:</strong> ${toolName}</p>
            <p><strong>Recommended:</strong> ${primary.label}</p>
            <p><strong>Results:</strong> <a href="${permalink}" style="color: ${C.TEAL};">${permalink}</a></p>
          </div>
          <p style="color: ${C.TEXT}; font-size: 14px;">Reply directly to this email to reach them.</p>
        </div>
      `,
    })

    return NextResponse.json({ message: 'Report sent successfully' }, { status: 200 })
  } catch (error) {
    console.error('API error:', error)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}
