import { Resend } from 'resend'
import { NextResponse } from 'next/server'

let resend = null
function getResend() {
  if (!resend) {
    resend = new Resend(process.env.RESEND_API_KEY)
  }
  return resend
}

const C = {
  TEAL: '#14b8a6',
  HEADING: '#333',
  SUBHEADING: '#555',
  TEXT: '#666',
  BG: '#f8f9fa',
  WHITE: '#fff',
  BORDER: '#e9ecef',
}

function buildEmailHtml({ recommended, alsoExplore, permalink }) {
  const alsoExploreHtml =
    alsoExplore.length > 0
      ? `
        <div style="margin-top: 24px;">
          <h3 style="color: ${C.SUBHEADING}; margin: 0 0 12px;">Also worth exploring</h3>
          ${alsoExplore
            .map(
              (result) =>
                `<div style="background: ${C.BG}; border-radius: 8px; padding: 14px 18px; margin-bottom: 10px;">
                  <h4 style="color: ${C.HEADING}; margin: 0 0 4px; font-size: 15px;">${result.title}</h4>
                  <p style="color: ${C.TEXT}; font-size: 13px; line-height: 1.5; margin: 0 0 8px;">${result.description}</p>
                  <a href="https://mitchellbryson.com/barnsley-ai/${result.slug}" style="color: ${C.TEAL}; font-size: 13px; font-weight: bold; text-decoration: none;">Learn more &rarr;</a>
                </div>`,
            )
            .join('')}
        </div>`
      : ''

  return `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
      <h2 style="color: ${C.HEADING}; border-bottom: 2px solid ${C.TEAL}; padding-bottom: 10px;">
        Your AI Integration Recommendation
      </h2>

      <div style="background: #f0fdfa; border: 2px solid ${C.TEAL}; border-radius: 12px; padding: 20px; margin: 20px 0;">
        <p style="font-size: 11px; font-weight: bold; text-transform: uppercase; letter-spacing: 0.5px; color: #0d9488; margin: 0 0 8px;">Recommended for your business</p>
        <h3 style="color: ${C.HEADING}; margin: 0 0 8px; font-size: 18px;">${recommended.title}</h3>
        <p style="color: ${C.TEXT}; font-size: 14px; line-height: 1.6; margin: 0 0 12px;">${recommended.description}</p>
        <a href="https://mitchellbryson.com/barnsley-ai/${recommended.slug}" style="display: inline-block; background: ${C.TEAL}; color: #fff; padding: 8px 20px; border-radius: 6px; text-decoration: none; font-size: 14px; font-weight: bold;">Learn more</a>
      </div>

      ${alsoExploreHtml}

      <div style="margin-top: 24px;">
        <h3 style="color: ${C.SUBHEADING}; margin: 0 0 12px;">What next?</h3>
        <table style="width: 100%; border-collapse: collapse;">
          <tr>
            <td style="padding: 8px 12px; vertical-align: top;">
              <span style="display: inline-block; width: 24px; height: 24px; line-height: 24px; text-align: center; border-radius: 50%; background: ${C.TEAL}; color: #fff; font-size: 12px; font-weight: bold;">1</span>
            </td>
            <td style="padding: 8px 12px; color: ${C.TEXT}; font-size: 14px; line-height: 1.5;">Read the full guide for your recommended integration to understand what it involves</td>
          </tr>
          <tr>
            <td style="padding: 8px 12px; vertical-align: top;">
              <span style="display: inline-block; width: 24px; height: 24px; line-height: 24px; text-align: center; border-radius: 50%; background: #d4d4d8; color: #52525b; font-size: 12px; font-weight: bold;">2</span>
            </td>
            <td style="padding: 8px 12px; color: ${C.TEXT}; font-size: 14px; line-height: 1.5;">Identify the specific bottleneck or process you want to address first</td>
          </tr>
          <tr>
            <td style="padding: 8px 12px; vertical-align: top;">
              <span style="display: inline-block; width: 24px; height: 24px; line-height: 24px; text-align: center; border-radius: 50%; background: #d4d4d8; color: #52525b; font-size: 12px; font-weight: bold;">3</span>
            </td>
            <td style="padding: 8px 12px; color: ${C.TEXT}; font-size: 14px; line-height: 1.5;">Get in touch to discuss a focused proof of concept for your business</td>
          </tr>
        </table>
      </div>

      <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid ${C.BORDER}; color: ${C.TEXT}; font-size: 13px;">
        <p>This report was generated by the <a href="${permalink || 'https://mitchellbryson.com/projects/tools/which-ai-integration'}" style="color: ${C.TEAL};">Which AI Integration?</a> tool on mitchellbryson.com.</p>
        <p>Want to discuss your results? <a href="https://mitchellbryson.com/contact" style="color: ${C.TEAL};">Get in touch</a>.</p>
      </div>
    </div>
  `
}

export async function POST(request) {
  try {
    const { email, toolName, permalink, recommended, alsoExplore } =
      await request.json()

    if (!email) {
      return NextResponse.json({ error: 'Email is required' }, { status: 400 })
    }

    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
    if (!emailRegex.test(email)) {
      return NextResponse.json({ error: 'Invalid email address' }, { status: 400 })
    }

    const r = getResend()

    // Send report to the user
    const { error } = await r.emails.send({
      from: `Mitchell Bryson <${process.env.CONTACT_EMAIL}>`,
      to: [email],
      subject: `Your AI Integration Recommendation: ${recommended.title}`,
      html: buildEmailHtml({ recommended, alsoExplore, permalink }),
    })

    if (error) {
      console.error('Resend error (report):', error)
      return NextResponse.json({ error: 'Failed to send report' }, { status: 500 })
    }

    // Notify Mitchell about the lead
    await r.emails.send({
      from: `Website <${process.env.CONTACT_EMAIL}>`,
      to: [process.env.CONTACT_EMAIL],
      subject: `${toolName}: new lead from ${email}`,
      replyTo: email,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h2 style="color: ${C.HEADING}; border-bottom: 2px solid ${C.TEAL}; padding-bottom: 10px;">
            New ${toolName} Lead
          </h2>
          <div style="background: ${C.BG}; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <p><strong>Email:</strong> ${email}</p>
            <p><strong>Tool:</strong> ${toolName}</p>
            <p><strong>Recommended:</strong> ${recommended.title}</p>
            <p><strong>Results:</strong> <a href="${permalink}" style="color: ${C.TEAL};">${permalink}</a></p>
          </div>
          <p style="color: ${C.TEXT}; font-size: 14px;">Reply directly to this email to reach them.</p>
        </div>
      `,
    })

    return NextResponse.json({ message: 'Report sent successfully' }, { status: 200 })
  } catch (error) {
    console.error('API error:', error)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}
