import { C, sendReportAndLead } from '@/lib/email'
import { siteUrl } from '@/lib/siteConfig'

function buildEmailHtml({ recommended, alsoExplore, permalink }) {
  const alsoExploreHtml =
    alsoExplore.length > 0
      ? `
        <div style="margin-top: 24px;">
          <h3 style="color: ${C.SUBHEADING}; margin: 0 0 12px;">Also worth exploring</h3>
          ${alsoExplore
            .map(
              (result) =>
                `<div style="background: ${C.BG}; border-radius: 8px; padding: 14px 18px; margin-bottom: 10px;">
                  <h4 style="color: ${C.HEADING}; margin: 0 0 4px; font-size: 15px;">${result.title}</h4>
                  <p style="color: ${C.TEXT}; font-size: 13px; line-height: 1.5; margin: 0 0 8px;">${result.description}</p>
                  <a href="${siteUrl}/barnsley-ai/${result.slug}" style="color: ${C.TEAL}; font-size: 13px; font-weight: bold; text-decoration: none;">Learn more &rarr;</a>
                </div>`,
            )
            .join('')}
        </div>`
      : ''

  return `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
      <h2 style="color: ${C.HEADING}; border-bottom: 2px solid ${C.TEAL}; padding-bottom: 10px;">
        Your AI Integration Recommendation
      </h2>

      <div style="background: #f0fdfa; border: 2px solid ${C.TEAL}; border-radius: 12px; padding: 20px; margin: 20px 0;">
        <p style="font-size: 11px; font-weight: bold; text-transform: uppercase; letter-spacing: 0.5px; color: #0d9488; margin: 0 0 8px;">Recommended for your business</p>
        <h3 style="color: ${C.HEADING}; margin: 0 0 8px; font-size: 18px;">${recommended.title}</h3>
        <p style="color: ${C.TEXT}; font-size: 14px; line-height: 1.6; margin: 0 0 12px;">${recommended.description}</p>
        <a href="${siteUrl}/barnsley-ai/${recommended.slug}" style="display: inline-block; background: ${C.TEAL}; color: #fff; padding: 8px 20px; border-radius: 6px; text-decoration: none; font-size: 14px; font-weight: bold;">Learn more</a>
      </div>

      ${alsoExploreHtml}

      <div style="margin-top: 24px;">
        <h3 style="color: ${C.SUBHEADING}; margin: 0 0 12px;">What next?</h3>
        <table style="width: 100%; border-collapse: collapse;">
          <tr>
            <td style="padding: 8px 12px; vertical-align: top;">
              <span style="display: inline-block; width: 24px; height: 24px; line-height: 24px; text-align: center; border-radius: 50%; background: ${C.TEAL}; color: #fff; font-size: 12px; font-weight: bold;">1</span>
            </td>
            <td style="padding: 8px 12px; color: ${C.TEXT}; font-size: 14px; line-height: 1.5;">Read the full guide for your recommended integration to understand what it involves</td>
          </tr>
          <tr>
            <td style="padding: 8px 12px; vertical-align: top;">
              <span style="display: inline-block; width: 24px; height: 24px; line-height: 24px; text-align: center; border-radius: 50%; background: #d4d4d8; color: #52525b; font-size: 12px; font-weight: bold;">2</span>
            </td>
            <td style="padding: 8px 12px; color: ${C.TEXT}; font-size: 14px; line-height: 1.5;">Identify the specific bottleneck or process you want to address first</td>
          </tr>
          <tr>
            <td style="padding: 8px 12px; vertical-align: top;">
              <span style="display: inline-block; width: 24px; height: 24px; line-height: 24px; text-align: center; border-radius: 50%; background: #d4d4d8; color: #52525b; font-size: 12px; font-weight: bold;">3</span>
            </td>
            <td style="padding: 8px 12px; color: ${C.TEXT}; font-size: 14px; line-height: 1.5;">Get in touch to discuss a focused proof of concept for your business</td>
          </tr>
        </table>
      </div>

      <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid ${C.BORDER}; color: ${C.TEXT}; font-size: 13px;">
        <p>This report was generated by the <a href="${permalink || siteUrl + '/projects/tools/which-ai-integration'}" style="color: ${C.TEAL};">Which AI Integration?</a> tool on mitchellbryson.com.</p>
        <p>Want to discuss your results? <a href="${siteUrl}/contact" style="color: ${C.TEAL};">Get in touch</a>.</p>
      </div>
    </div>
  `
}

export async function POST(request) {
  const { email, toolName, permalink, recommended, alsoExplore } =
    await request.json()

  return sendReportAndLead({
    email,
    toolName,
    permalink,
    subject: `Your AI Integration Recommendation: ${recommended.title}`,
    html: buildEmailHtml({ recommended, alsoExplore, permalink }),
    leadSummaryHtml: `<p><strong>Recommended:</strong> ${recommended.title}</p>`,
  })
}
