import { Resend } from 'resend'
import { NextResponse } from 'next/server'

let resend = null
function getResend() {
  if (!resend) {
    resend = new Resend(process.env.RESEND_API_KEY)
  }
  return resend
}

const C = {
  TEAL: '#14b8a6',
  HEADING: '#333',
  SUBHEADING: '#555',
  TEXT: '#666',
  BG: '#f8f9fa',
  BORDER: '#e9ecef',
}

function buildEmailHtml({ cheapestModel, cheapestProvider, cheapestMonthly, inputTokens, outputTokens, requestsPerDay, costs, permalink }) {
  const costRows = costs
    .map(
      (m, i) =>
        `<tr style="border-bottom: 1px solid ${C.BORDER}; ${i === 0 ? 'background: #f0fdfa;' : ''}">
          <td style="padding: 10px 16px;">
            <strong style="color: ${i === 0 ? '#0d9488' : C.HEADING};">${m.name}</strong>
            <br/><span style="font-size: 12px; color: ${C.TEXT};">${m.provider}</span>
          </td>
          <td style="padding: 10px 16px; text-align: right; color: ${i === 0 ? '#0d9488' : C.TEXT};">${m.perRequest}</td>
          <td style="padding: 10px 16px; text-align: right; color: ${i === 0 ? '#0d9488' : C.TEXT};">${m.daily}</td>
          <td style="padding: 10px 16px; text-align: right; color: ${i === 0 ? '#0d9488' : C.TEXT}; font-weight: ${i === 0 ? 'bold' : 'normal'};">${m.monthly}</td>
        </tr>`,
    )
    .join('')

  return `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
      <h2 style="color: ${C.HEADING}; border-bottom: 2px solid ${C.TEAL}; padding-bottom: 10px;">
        Your LLM Cost Comparison
      </h2>

      <div style="background: #f0fdfa; border: 2px solid ${C.TEAL}; border-radius: 12px; padding: 20px; margin: 20px 0;">
        <p style="font-size: 11px; font-weight: bold; text-transform: uppercase; letter-spacing: 0.5px; color: #0d9488; margin: 0 0 8px;">Most cost-effective</p>
        <h3 style="color: ${C.HEADING}; margin: 0 0 4px; font-size: 18px;">${cheapestModel}</h3>
        <p style="color: ${C.TEXT}; font-size: 14px; margin: 0;">${cheapestMonthly}/month &middot; ${cheapestProvider}</p>
      </div>

      <div style="background: ${C.BG}; border-radius: 8px; padding: 14px 18px; margin-bottom: 20px;">
        <p style="color: ${C.TEXT}; font-size: 13px; margin: 0;">
          <strong>Your inputs:</strong> ${Number(inputTokens).toLocaleString()} input tokens, ${Number(outputTokens).toLocaleString()} output tokens, ${Number(requestsPerDay).toLocaleString()} requests/day
        </p>
      </div>

      <table style="width: 100%; border-collapse: collapse; font-size: 13px;">
        <thead>
          <tr style="border-bottom: 2px solid ${C.BORDER};">
            <th style="padding: 8px 16px; text-align: left; color: ${C.SUBHEADING};">Model</th>
            <th style="padding: 8px 16px; text-align: right; color: ${C.SUBHEADING};">Per request</th>
            <th style="padding: 8px 16px; text-align: right; color: ${C.SUBHEADING};">Daily</th>
            <th style="padding: 8px 16px; text-align: right; color: ${C.SUBHEADING};">Monthly</th>
          </tr>
        </thead>
        <tbody>
          ${costRows}
        </tbody>
      </table>

      <p style="color: #a1a1aa; font-size: 12px; margin-top: 16px;">Prices are approximate and based on publicly listed API pricing as of early 2025.</p>

      <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid ${C.BORDER}; color: ${C.TEXT}; font-size: 13px;">
        <p>This report was generated by the <a href="${permalink || 'https://mitchellbryson.com/projects/tools/llm-cost-calculator'}" style="color: ${C.TEAL};">LLM Cost Calculator</a> tool on mitchellbryson.com.</p>
        <p>Want to discuss your results? <a href="https://mitchellbryson.com/contact" style="color: ${C.TEAL};">Get in touch</a>.</p>
      </div>
    </div>
  `
}

export async function POST(request) {
  try {
    const { email, toolName, permalink, cheapestModel, cheapestProvider, cheapestMonthly, inputTokens, outputTokens, requestsPerDay, costs } =
      await request.json()

    if (!email) {
      return NextResponse.json({ error: 'Email is required' }, { status: 400 })
    }

    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
    if (!emailRegex.test(email)) {
      return NextResponse.json({ error: 'Invalid email address' }, { status: 400 })
    }

    const r = getResend()

    const { error } = await r.emails.send({
      from: `Mitchell Bryson <${process.env.CONTACT_EMAIL}>`,
      to: [email],
      subject: `Your LLM Cost Comparison: ${cheapestModel} from ${cheapestMonthly}/mo`,
      html: buildEmailHtml({ cheapestModel, cheapestProvider, cheapestMonthly, inputTokens, outputTokens, requestsPerDay, costs, permalink }),
    })

    if (error) {
      console.error('Resend error (LLM cost report):', error)
      return NextResponse.json({ error: 'Failed to send report' }, { status: 500 })
    }

    await r.emails.send({
      from: `Website <${process.env.CONTACT_EMAIL}>`,
      to: [process.env.CONTACT_EMAIL],
      subject: `${toolName}: new lead from ${email}`,
      replyTo: email,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h2 style="color: ${C.HEADING}; border-bottom: 2px solid ${C.TEAL}; padding-bottom: 10px;">
            New ${toolName} Lead
          </h2>
          <div style="background: ${C.BG}; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <p><strong>Email:</strong> ${email}</p>
            <p><strong>Tool:</strong> ${toolName}</p>
            <p><strong>Cheapest:</strong> ${cheapestModel} at ${cheapestMonthly}/mo</p>
            <p><strong>Results:</strong> <a href="${permalink}" style="color: ${C.TEAL};">${permalink}</a></p>
          </div>
          <p style="color: ${C.TEXT}; font-size: 14px;">Reply directly to this email to reach them.</p>
        </div>
      `,
    })

    return NextResponse.json({ message: 'Report sent successfully' }, { status: 200 })
  } catch (error) {
    console.error('API error:', error)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}
